# Generated by Django 5.2 on 2026-04-13 18:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('dining', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_flujo', models.CharField(choices=[('MESA', 'Mesa'), ('RAPIDO', 'Rápido')], max_length=16)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CONFIRMADO', 'Confirmado'), ('PAGADO_PARCIAL', 'Pagado parcial'), ('COMPLETADO', 'Completado'), ('ANULADO', 'Anulado')], max_length=32)),
                ('total_bruto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('propina_monto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='dining.diningtable')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.tenant')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
