# Generated by Django 5.2 on 2026-04-16 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_product_image_product_image_url'),
        ('core', '0005_rolepermission_active_rolepermission_updated_at_and_more'),
        ('orders', '0003_transaction_transactionitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('IMPRESORA', 'Impresora'), ('PANTALLA', 'Pantalla')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='core.tenant')),
            ],
            options={
                'ordering': ('tenant', 'nombre'),
                'unique_together': {('tenant', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('LISTA', 'Lista'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandas', to='orders.order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandas', to='core.tenant')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandas', to='orders.dispositivo')),
            ],
            options={
                'ordering': ('-creado_en',),
            },
        ),
        migrations.CreateModel(
            name='ComandaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(help_text='Cantidad snapshot del order item en el momento de asignación a la comanda')),
                ('precio_unitario_snapshot', models.DecimalField(decimal_places=2, help_text='Precio unitario snapshot del order item en el momento de asignación', max_digits=12)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.comanda')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orders.orderitem')),
            ],
            options={
                'verbose_name': 'Ítem de Comanda',
                'verbose_name_plural': 'Ítems de Comanda',
                'unique_together': {('comanda', 'order_item')},
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.category')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_dispositivo', to='core.tenant')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones', to='orders.dispositivo')),
            ],
            options={
                'verbose_name': 'Configuración de Dispositivo',
                'verbose_name_plural': 'Configuraciones de Dispositivos',
                'ordering': ('tenant', '-prioridad'),
                'unique_together': {('tenant', 'dispositivo', 'categoria'), ('tenant', 'dispositivo', 'producto')},
            },
        ),
    ]
