# Generated by Django 5.2 on 2026-04-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_transaction_tip_and_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='propina_monto',
        ),
    ]
