# Generated by Django 5.2 on 2026-04-28 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rolepermission_active_rolepermission_updated_at_and_more'),
        ('orders', '0009_seed_cash_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashsession',
            name='comentario_cierre',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='CashCloseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_sistema', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_declarado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cash_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_details', to='orders.cashsession')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_close_details', to='orders.paymentmethod')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_close_details', to='core.tenant')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('cash_session', 'payment_method')},
            },
        ),
    ]
