# Generated by Django 5.2 on 2026-04-28 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_cashsession_comentario_cierre_cashclosedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmovement',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='orders.paymentmethod'),
        ),
    ]
