# Generated by Django 5.2 on 2026-04-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_cashmovement_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashclosedetail',
            name='comentario',
            field=models.TextField(blank=True, default=''),
        ),
    ]
