# Generated by Django 5.2 on 2026-04-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_cashclosedetail_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='inhabilitado',
            field=models.BooleanField(default=False, help_text='Inhabilitación permanente — no se puede reactivar'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='activo',
            field=models.BooleanField(default=True, help_text='Pausa temporal (método fuera de uso temporal)'),
        ),
    ]
