# Generated by Django 5.2 on 2026-04-13 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=32)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADA', 'Ocupada'), ('PAGANDO', 'Pagando'), ('RESERVADA', 'Reservada')], default='DISPONIBLE', max_length=32)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dining_tables', to='core.tenant')),
            ],
            options={
                'ordering': ('tenant', 'numero'),
                'unique_together': {('tenant', 'numero')},
            },
        ),
    ]
