# Generated by Django 5.2 on 2026-04-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rolepermission_active_rolepermission_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
