# Generated by Django 5.2 on 2026-04-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_role_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='inhabilitado',
            field=models.BooleanField(default=False, help_text='Inhabilitación permanente — no puede volver a activarse'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pausado',
            field=models.BooleanField(default=False, help_text='Pausa temporal (vacaciones, licencia)'),
        ),
        migrations.AddField(
            model_name='role',
            name='inhabilitado',
            field=models.BooleanField(default=False, help_text='Inhabilitación permanente — no se puede reactivar'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Pausa temporal (roles de uso esporádico)'),
        ),
    ]
