# Generated by Django 5.2 on 2026-04-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_product_image_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='inhabilitado',
            field=models.BooleanField(default=False, help_text='Inhabilitación permanente — no se puede reactivar'),
        ),
        migrations.AddField(
            model_name='product',
            name='inhabilitado',
            field=models.BooleanField(default=False, help_text='Inhabilitación permanente — no se puede reactivar'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Pausa temporal (productos estacionales, fuera de temporada)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Pausa temporal (productos estacionales, fuera de temporada)'),
        ),
    ]
